# Generated by Django 2.1.15 on 2020-04-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_status_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assignee',
        ),
    ]
