# Generated by Django 2.1.15 on 2020-04-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['date']},
        ),
    ]
