# Generated by Django 2.1.15 on 2020-04-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_auto_20200430_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
